#!/bin/bash
#
# Create a trash setup, serving it via HTTP.
#


#
#  The directory we'll use.
#
tmp=~/.trash.d/http

#
#  Where we are.
#
dir=$(pwd)

#
# Remove it and recreate it
#
test -d $tmp && rm -rf $tmp
mkdir -p $tmp

#
#  create a stub repository with a simple set of policies.
#
mkdir -p $tmp/files/
mkdir -p $tmp/policies/
cat > $tmp/policies/default.policy <<EOF

#
# Include a policy based on hostname
#
FetchPolicy \$fqdn.policy;

#
#  Fetch a shell command policy
#
FetchPolicy cmd.policy;
EOF

cat > $tmp/policies/$(hostname).policy <<EOF
 print "I am \$fqdn\n";
EOF
cat > $tmp/policies/cmd.policy <<EOF
  RunCommand( Cmd => "uptime" );
EOF

#
#  Start httpd
#
cd $tmp

cat >/tmp/thttpd.conf <<EOF
host=127.0.0.1
port=2222
dir=$tmp
pidfile=/tmp/thttpd.conf.pid
EOF

thttpd -C /tmp/thttpd.conf

#
#  Now use the HTTP transport to work with http://localhost:2222/
#
cd $dir
sudo perl -I./lib ./bin/slaughter-2 --transport=http --prefix=http://127.0.0.1:2222 --verbose --no-delete


#
#  Run two - try again with htaccess
#
echo 'steve:QzhWLEpEM4Rx6' > $tmp/.htpasswd
echo 'steve:QzhWLEpEM4Rx6' > $tmp/files/.htpasswd
echo 'steve:QzhWLEpEM4Rx6' > $tmp/policies/.htpasswd
cd $dir
sudo perl -I./lib ./bin/slaughter-2 --transport=http --prefix=http://127.0.0.1:2222 --verbose --no-delete --username=steve --password=kemp



#
#  Kill the httpd
#
kill -9 $(cat /tmp/thttpd.conf.pid)
