#!/bin/bash
#
# Create a trash mercurial repository, and use that as a source
#


#
#  The directory we'll use.
#
hg=~/hg/trash.d


#
# Remove it and recreate it
test -d $hg && rm -rf $hg
mkdir -p $hg

#
#  create a stub repository with a simple policy
#
mkdir -p $hg/files/
mkdir -p $hg/policies/
cat > $hg/policies/default.policy <<EOF

#
# Include a policy based on hostname
#
FetchPolicy \$fqdn.policy;

#
#  Fetch a shell command policy
#
FetchPolicy cmd.policy;

#
#  Copy a file
#
FetchPolicy motd.policy;

EOF


cat > $hg/policies/$(hostname).policy <<EOF
 print "I am \$fqdn\n";
EOF

cat > $hg/policies/cmd.policy <<EOF
  RunCommand( Cmd => "uptime" );
EOF

cat > $hg/policies/motd.policy <<EOF
if ( FetchFile(
            Source => "/etc/motd",
              Dest => "/etc/motd",
            Expand => "true",
             Owner => "root",
             Group => "root",
              Mode => "644" ) )
{
print "Replaced file: /etc/motd\n";
}
EOF

mkdir -p $hg/files/etc/

cat > $hg/files/etc/motd <<EOF
  This is the MOTD file for {\$fqdn}
EOF


#
#  Initialize the repository and add the contents to it.
#
pushd $hg && hg init && popd
pushd $hg && hg add files && popd
pushd $hg && hg add policies && popd
pushd $hg && hg commit "-m added" && popd

pwd
#
#  Now clone from that repository
#
sudo perl -I./lib ./bin/slaughter --transport=hg --prefix=$hg --verbose --no-delete
